CREATE CONSTRAINT ON (r:Role) ASSERT r.id IS UNIQUE;
CREATE CONSTRAINT ON (p:Permission) ASSERT p.id IS UNIQUE;
CREATE CONSTRAINT ON (l:Location) ASSERT l.sapid IS UNIQUE;
CREATE CONSTRAINT ON (u:User) ASSERT u.federationId IS UNIQUE;